name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "We will get to this asap until then join our discord for updates https://discord.gg/mfpwe3rRyP"
        pr-message: "Thanks for contributing to this project, We understand the value of this to you and we will try to get to you asap until then, join our discord for updates https://discord.gg/mfpwe3rRyP"
